# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  frontend:
    image: idea2tasksfrontend
    build:
      context: ./Idea2Tasks.Frontend
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - ./Idea2Tasks.Frontend:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - CHOKIDAR_USEPOLLING=true

    command: npm run dev -- --host

    stdin_open: true
    tty: true

  backend:
    image: idea2tasksbackend
    build:
      context: .
      dockerfile: Idea2Tasks.Backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/Idea2Task.db
      - AppSettings__ApiKey= ${APP_API_KEY}
    volumes:
      - ./Idea2Tasks.Backend/Data:/app/data
