using System.Text.Json;
using Idea2Tasks.Data;
using Idea2Tasks.DTO;
using Idea2Tasks.Models;
using Idea2Tasks.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Idea2Tasks.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProjectController : ControllerBase
    {
        private readonly AppDb appDb;
        private readonly GeminiService geminiService;

        public ProjectController(AppDb appDb, GeminiService geminiService)
        {
            this.appDb = appDb;
            this.geminiService = geminiService;
        }

        [HttpPost]
        public async Task<ActionResult<ProjectDTO>> AddProject(ProjectDTO projectDTO)
        {
            var project = new Project
            {
                Name = projectDTO.Name,
                Description = projectDTO.Description,
                IsCompleted = projectDTO.IsCompleted,
                // SubTasks = projectDTO.SubTasks?.Select(s => new SubTask
                // {
                //     Description = s.Description,
                //     IsCompleted = s.IsCompleted,
                //     Duration = s.Duration,
                //     Project = null!
                // }).ToList() ?? new List<SubTask>()
            };

            string generatedContent = string.Empty;

            try
            {
                generatedContent = await geminiService.GenerateProjectTasksAsync(project.Name, project.Description);
                Console.WriteLine("Gemini Response:\n" + generatedContent);

                // Optional: strip markdown if Gemini added it
                generatedContent = generatedContent.Replace("```json", "").Replace("```", "").Trim();

                // Deserialize AI subtasks (case-insensitive)
                var aiSubTasks = JsonSerializer.Deserialize<List<SubTaskDTO>>(
                    generatedContent,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                if (aiSubTasks != null && aiSubTasks.Count > 0)
                {
                    foreach (var s in aiSubTasks)
                    {
                        project.SubTasks.Add(new SubTask
                        {
                            Description = s.Description,
                            IsCompleted = s.IsCompleted,
                            Duration = s.Duration,
                            Project = project
                        });
                    }
                }
                else
                {
                    // Fallback if JSON is empty
                    project.Description += "\n\n[Gemini returned empty subtasks]\n" + generatedContent;
                }
            }
            catch (Exception ex)
            {
                // Save raw content if deserialization fails
                Console.WriteLine("Gemini parsing failed: " + ex.Message);
                project.Description += "\n\n[Generated by Gemini]\n" + generatedContent;
            }

            await appDb.Projects.AddAsync(project);
            await appDb.SaveChangesAsync();

            var fullProject = await appDb.Projects
                .Include(p => p.SubTasks)
                .FirstOrDefaultAsync(p => p.Id == project.Id);

            return Ok(MapProjectToDTO(fullProject!));
        }
        
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ProjectDTO>>> GetAllProjects()
        {
            var projects = await appDb.Projects
                .Include(p => p.SubTasks)
                .ToListAsync();

            var projectDTOs = projects.Select(MapProjectToDTO).ToList();

            return Ok(projectDTOs);
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<ProjectDTO>> GetProject(int id)
        {
            var project = await appDb.Projects
                .Include(p => p.SubTasks)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project == null)
                return NotFound();

            return Ok(MapProjectToDTO(project));
        }

        [HttpPut("{id}")]
        public async Task<ActionResult> UpdateProjectById(int id, ProjectDTO projectDTO)
        {
            var project = await appDb.Projects
                .Include(p => p.SubTasks)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project == null)
                return NotFound();

            project.Name = projectDTO.Name;
            project.Description = projectDTO.Description;
            project.IsCompleted = projectDTO.IsCompleted;

            await appDb.SaveChangesAsync();

            return NoContent();
        }

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteProjectById(int id)
        {
            var project = await appDb.Projects.FindAsync(id);

            if (project == null)
                return NotFound();

            appDb.Projects.Remove(project);
            await appDb.SaveChangesAsync();

            return NoContent();
        }

        private static ProjectDTO MapProjectToDTO(Project project)
        {
            return new ProjectDTO
            {
                Name = project.Name,
                Description = project.Description,
                IsCompleted = project.IsCompleted,
                SubTasks = project.SubTasks.Select(s => new SubTaskDTO
                {
                    Id = s.Id,
                    Description = s.Description,
                    IsCompleted = s.IsCompleted,
                    Duration = s.Duration,
                    ProjectId = s.ProjectId
                }).ToList()
            };
        }
    }
}